# Generated by Django 3.1.2 on 2021-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True)),
                ('position', models.CharField(choices=[('', ''), ('Coordinator', 'Coordinator'), ('Executive Member', 'Executive Member'), ('Alumnus', 'Alumnus'), ('Volunteer', 'Volunteer')], db_index=True, max_length=100)),
                ('tagline', models.CharField(max_length=300)),
                ('imageURL', models.URLField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
