# Generated by Django 3.1.4 on 2021-01-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Coordinator', 'Coordinator'), ('Executive Member', 'Executive Member'), ('Alumnus', 'Alumnus'), ('Volunteer', 'Volunteer')], db_index=True, max_length=100),
        ),
    ]
