# Generated by Django 3.1.2 on 2021-01-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210125_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
